### PR TITLE
vend: Correctly copy replaced modules to their replacement directory.

### PR DESCRIPTION
**Pull request by c00w**

### CODE REVIEW

**Comment by nomad-software** [comment]
Hi, thanks for the pull request, what does it do and more importantly why?

**Comment by c00w** [comment]
Let say you have go.mod
```
module example

go 1.14

require(
  foo.com/bar v1
)

replace foo.com/bar => bar.com/bar v1.0
```

Currently vend will download bar.com/bar (good), since that's what go mod download -json tells it about (correct). However, it needs to be accessible at foo.com/bar since it's replacing that module. It's not currently moved there, which breaks the import. Instead, this patch copes bar.com/bar to foo.com/bar, which allows the import to work.

**Comment by nomad-software** [comment]
I still not sure they should be supported. It's come up before here: https://github.com/nomad-software/vend/issues/1#issuecomment-448691520 and I think I still agree with that. i.e. "The use cases for replace statements tend to be for development or for debugging not really candidates for long-term archiving of dependencies."

**Comment by c00w** [comment]
go mod vendor handles this correctly - your tool doesn't + real software running in the wild uses this (generally to override a package that a dependency is using).

I don't have huge objections to maintaining a permanent hard fork, but it seems silly to have two alternate vendor tools in the wild :(

As a side note - it seems like basically no new features are getting accepted - Is that an intentional decision? I.e. should I just stop opening PRs? Or are you open to new features, just not the specific features I needed?

**Comment by nomad-software** [comment]
Lemme think about it tonight.

**Comment by nomad-software** [comment]
Ok, I'll have a play with this branch this afternoon and if it works ok i'll get it merged. I just want to make sure all cases are covered.

**Comment by nomad-software** [comment]
I've had a look at this and I don't think it works.
The source and destination are both defined residing in the vendor directory (which seems wrong) and there's no handling of versions, etc.

I reverted to `master` and I trying adding this line in the `go.mod` file:
```
replace github.com/fatih/color => github.com/fatih/color v1.6.0
```
and `vend` copied the correct version without any code changes. So is a PR such as this necessary at all?

EDIT: I'm using Go v1.5rc1

**Comment by c00w** [comment]
@nomad-software So I think the issue is that the bug only happens when you replace one repo with a different repo.

I.e. https://github.com/tulir/mautrix-whatsapp/blob/master/go.mod

If you replace fatih-color with the same repo at a different version go mod download json will return the right revision + repo.

However in the rename case i.e. 
github.com/Rhymen/go-whatsapp => github.com/tulir/go-whatsapp v0.3.4

what happens is go mod downloadjson return tulir/go-whatsapp v0.3.4 which gets downloaded. But the existing code wants to import github.com/Rhymen/go-whatsapp, and fails.

This code copies the folder over (which should be a noop if they are the same folder), but fixes the issues when the replace is downloading a different module path than what it's replacing.

Edit

Also let me know if you want me to manually confirm the second case I'm talking about with go1.15 - I don't want to waste your time if you were already aware of the case I'm talking about above + it also worked with go1.15.

**Comment by c00w** [comment]
Also just to confirm (I think you're implicitly saying this by mentioning you were ok to merge if no bugs were found), but having a goal (if not the current feature set), to build most go software and github that people use is reasonable and bug fixes / features in support of it match your ideas for what should be merged?

**Comment by c00w** [comment]
Turns out if the rewrite was to the same folder, there was a bug which caused empty files in some cases - new commits pushed to fix it.

**Comment by nomad-software** [comment]
> Turns out if the rewrite was to the same folder, there was a bug which caused empty files in some cases - new commits pushed to fix it.
That was a bug I encountered too.

There is a problem still in that this change doesn't handle replacements from the local file system.

> The replace directive allows you to supply another import path that might be another module located in VCS (GitHub or elsewhere), or on your **local filesystem with a relative or absolute file path**. 

https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

I'm going to close this now as every time I test it I find new bugs. Any change to handle replacements must handle _all_ cases in a consistent and bug free manner.

You are welcome to submit another PR but all scenarios list in the above documentation must be fully tested before submission.

**Comment by nomad-software** [comment]
I might take a look at adding this myself.

**Comment by c00w** [comment]
The existing vend code actually fails with a local replacement (or more accurately, succeeds but then the build fails) - which is probably worse :)

I've added the 3 lines of code required to fix local paths :)

**Comment by Mic92** [comment]
> > Turns out if the rewrite was to the same folder, there was a bug which caused empty files in some cases - new commits pushed to fix it.
> > That was a bug I encountered too.
> 
> There is a problem still in that this change doesn't handle replacements from the local file system.
> 
> > The replace directive allows you to supply another import path that might be another module located in VCS (GitHub or elsewhere), or on your **local filesystem with a relative or absolute file path**.
> 
> [golang/go/wiki/Modules#when-should-i-use-the-replace-directive](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive)
> 
> I'm going to close this now as every time I test it I find new bugs. Any change to handle replacements must handle _all_ cases in a consistent and bug free manner.
> 
> You are welcome to submit another PR but all scenarios list in the above documentation must be fully tested before submission.

This is a weird approach to PRs. Usually open source projects encourage to do early draft pull requests to give feedback in case the pull request develops in the wrong direction.

**Pull request closed without merging**
